<a href="https://colab.research.google.com/github/kanwar-sidhu/cardekho-price-car-/blob/main/Cleanning_car_dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [132]:
df = pd.read_csv("https://raw.githubusercontent.com/kanwar-sidhu/cardekho-price-car-/main/car_price_predict.csv") #data taken from kaggle cardekho website
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [133]:
df.shape

(4340, 8)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

#Data Cleaning

Check nan Value

In [135]:
df.isna().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

Check Duplicate

In [136]:
df.duplicated().sum()

763

In [137]:
df.drop_duplicates(inplace=True)

In [138]:
df.duplicated().sum()

0

Check Unique Value

In [139]:
df.nunique()

name             1491
year               27
selling_price     445
km_driven         770
fuel                5
seller_type         3
transmission        2
owner               5
dtype: int64

In [140]:
df.describe()

              year  selling_price      km_driven
count  3577.000000   3.577000e+03    3577.000000
mean   2012.962538   4.739125e+05   69250.545709
std       4.251759   5.093018e+05   47579.940016
min    1992.000000   2.000000e+04       1.000000
25%    2010.000000   2.000000e+05   36000.000000
50%    2013.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [141]:
#In {owner} coloumn remove owner from first owner
df['owner'] = df['owner'].str.replace(' Owner', '')

In [142]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First

In [143]:
#make all string values in data set (lower case)
for column in df.select_dtypes(include=[object]):
    df[column] = df[column].str.lower()

In [144]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
3,datsun redigo t option,2017,250000,46000,petrol,individual,manual,first
4,honda amaze vx i-dtec,2014,450000,141000,diesel,individual,manual,second
...,...,...,...,...,...,...,...,...
4335,hyundai i20 magna 1.4 crdi (diesel),2014,409999,80000,diesel,individual,manual,second
4336,hyundai i20 magna 1.4 crdi,2014,409999,80000,diesel,individual,manual,second
4337,maruti 800 ac bsiii,2009,110000,83000,petrol,individual,manual,second
4338,hyundai creta 1.6 crdi sx option,2016,865000,90000,diesel,individual,manual,first
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [145]:
#check unique category in each coloumn
categorical_column = ['name','year','fuel','seller_type','transmission','owner',]

for col in categorical_column:
    print(f"Category in {col} is : {df[col].unique()}")

Category in name is : ['maruti 800 ac' 'maruti wagon r lxi minor' 'hyundai verna 1.6 sx' ...
 'mahindra verito 1.5 d6 bsiii'
 'toyota innova 2.5 vx (diesel) 8 seater bs iv'
 'hyundai i20 magna 1.4 crdi']
Category in year is : [2007 2012 2017 2014 2016 2015 2018 2019 2013 2011 2010 2009 2006 1996
 2005 2008 2004 1998 2003 2002 2020 2000 1999 2001 1995 1997 1992]
Category in fuel is : ['petrol' 'diesel' 'cng' 'lpg' 'electric']
Category in seller_type is : ['individual' 'dealer' 'trustmark dealer']
Category in transmission is : ['manual' 'automatic']
Category in owner is : ['first' 'second' 'fourth & above' 'third' 'test drive car']

In [146]:
frequency = ['name','year','fuel','seller_type','transmission','owner']

for fre in frequency:
    print(f"frequency in {fre} is : {df[fre].value_counts()}")

frequency in name is : maruti swift dzire vdi             64
maruti alto 800 lxi                48
maruti alto lxi                    46
maruti alto lx                     30
hyundai eon era plus               28
                                   ..
hyundai elantra sx                  1
datsun redi-go amt 1.0 t option     1
bmw x1 sdrive20d m sport            1
honda amaze s diesel                1
hyundai i20 magna 1.4 crdi          1
Name: name, Length: 1475, dtype: int64
frequency in year is : 2017    346
2012    338
2015    332
2014    321
2013    298
2018    295
2016    283
2011    247
2010    210
2009    169
2019    162
2008    129
2007    117
2006     93
2005     61
2020     45
2004     38
2003     22
2002     18
2001     16
2000     12
1998      9
1999      9
1997      3
1996      2
1995      1
1992      1
Name: year, dtype: int64
frequency in fuel is : diesel      1800
petrol      1717
cng           37
lpg           22
electric       1
Name: fuel, dtype: int64
frequency in seller_type is : individual          2832
dealer               712
trustmark dealer      33
Name: seller_type, dtype: int64
frequency in transmission is : manual       3265
automatic     312
Name: transmission, dtype: int64
frequency in owner is : first             2218
second             978
third              289
fourth & above      75
test drive car      17
Name: owner, dtype: int64

In [147]:
# Identify names with counts greater than 10
frequent_names = df['name'].value_counts()
frequent_names = frequent_names[frequent_names > 10].index.tolist()

# Filter the DataFrame based on these names
df = df[df['name'].isin(frequent_names)]
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4325,maruti alto lxi,2000,65000,90000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [148]:
# Since the DataFrame is already filtered by 'name', recalculate 'year' value counts
frequent_years = df['year'].value_counts()
frequent_years = frequent_years[frequent_years > 5].index.tolist()

# Further filter the DataFrame based on these years
df = df[df['year'].isin(frequent_years)]
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4321,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [149]:
# Since the DataFrame is now filtered by both 'name' and 'year', recalculate 'fuel' value counts
frequent_fuels = df['fuel'].value_counts()
frequent_fuels = frequent_fuels[frequent_fuels > 20].index.tolist()

# Further filter the DataFrame based on these fuel types
df = df[df['fuel'].isin(frequent_fuels)]
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4321,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [150]:
# Since the DataFrame is now filtered by both 'name' and 'year', recalculate 'seller_type' value counts
frequent_seller = df['seller_type'].value_counts()
frequent_seller = frequent_seller[frequent_seller > 35].index.tolist()

# Further filter the DataFrame based on these seller types
df = df[df['seller_type'].isin(frequent_seller)]
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4321,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [151]:
# Since the DataFrame is now filtered by both 'name' and 'year', recalculate 'owner' value counts
frequent_owner = df['owner'].value_counts()
frequent_owner = frequent_owner[frequent_owner > 20].index.tolist()

# Further filter the DataFrame based on these owner types
df = df[df['owner'].isin(frequent_owner)]
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4321,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [152]:
df.owner.value_counts()

first     388
second    218
third      66
Name: owner, dtype: int64

In [153]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
49,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
51,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
4321,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
4322,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
4323,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
4333,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
4339,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [154]:
# Reset the index and drop the old one
df= df.reset_index(drop=True)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,maruti 800 ac,2007,60000,70000,petrol,individual,manual,first
1,maruti wagon r lxi minor,2007,135000,50000,petrol,individual,manual,first
2,hyundai verna 1.6 sx,2012,600000,100000,diesel,individual,manual,first
3,maruti wagon r vxi bs iv,2012,275000,60000,petrol,individual,manual,second
4,hyundai santro xing gls,2009,150000,79000,petrol,individual,manual,third
...,...,...,...,...,...,...,...,...
667,maruti alto lx,2006,75000,130000,petrol,individual,manual,first
668,hyundai verna 1.6 sx crdi (o),2013,500000,120000,diesel,individual,manual,first
669,maruti 800 ac,2014,195000,75000,petrol,individual,manual,second
670,maruti ritz vdi,2012,225000,90000,diesel,individual,manual,second
671,renault kwid rxt,2016,225000,40000,petrol,individual,manual,first

In [156]:
df.to_csv('Cleaned_data_car.csv', index=False)